#!/bin/sh
# AoC 2020 day 05

[ "$1" = -h ] && echo 'Usage: main FILE [12]' && exit
part="${1:-1}"
input="${2:-input.txt}"

lines=$(sed -E "s/([BF])([LR])/\1 \2/g;s/F/0/g;s/B/1/g;s/R/1/g;s/L/0/g" "$input" |
	awk 'func btod(b) {
			i=0; x=0
			len=length(b)
			while(len) {
				len=length(b)
				d=substr(b,len,1)
				b=substr(b,0,len-1)
			    x+=d*2^i; i++
			}
			return x
		}
	{print btod($1)*8+btod($2)}' |
		sort -n)

case "$part" in
	1) answer="$(echo "$lines" | tail -n 1)"
		;;
	2) answer="$(echo "$lines" | awk '$1==prev+2 {print prev+1} {prev=$1}')"
esac

echo "The answer for part ${part} is: $answer"
