#!/bin/sh
# AoC 2020 day 04

input="${1:-input.txt}"

lines=$(sed -zr "s/\n{2}/X/g;s/\n/ /g;s/X/\n/g" "$input")

echo "$lines" |
	awk '/byr:/ && /iyr:/ && /eyr:/ && /hgt:/ && /hcl:/ && /ecl:/ && /pid:/' |
	wc -l

echo "$lines" |
	grep -E "byr:(19[2-9][0-9]|200[0-2])" |
	grep -E "iyr:20(1[0-9]|20)" |
	grep -E "eyr:20(2[0-9]|30)" |
	grep -E "hgt:(1([5-8][0-9]|9[0-3])cm|(59|6[0-9]|7[0-6])in)" |
	grep -E "hcl:#[0-9a-f]{6}( |$)" |
	grep -E "ecl:(amb|blu|brn|gry|grn|hzl|oth)" |
	grep -E "pid:[0-9]{9}( |$)" |
	wc -l
