#!/bin/sh
# AoC 2020 day 08

input=${1:-input.txt}

cat "$input" | awk '
func interpret_line(op, arg) {
	if(op ~ "acc"){ acc += arg; cur+=1 }
		else if(op ~ "jmp"){ cur+=arg }
		else if(op ~ "nop"){ cur+=1 }
}
{
	a[NR] = $1 FS $2 FS NR
}
END {
	cur = 1
		while(!visited[cur]) {
			split(a[cur], _args)
			visited[_args[3]]++
			interpret_line(_args[1], _args[2])
		}
	print acc
}
'
