run *args:
  cargo run {{args}}
build *args:
  cargo build {{args}}
test *args:
  cargo test {{args}}
bench *args:
  cargo bench {{args}}
scaffold day:
  ./scripts/scaffold-day.sh {{day}}
write-bench:
  ./scripts/write-benchmarks-to-readme.sh
write-bench-console:
  cargo bench --bench criterion -- --output-format=bencher -n
