#!/bin/sh
# AoC 2020 day 02

input=${1:-input.txt}

sed -E 's/:/,/g;s/([0-9]) /\1, /g;s/\n/, /g;s/^/\[/;s/$/\], /' "$input" | sed -zE 's/\n//g;s/^/\[/;s/, $/\]\./' > input_transformed.txt

sicstus --nologo -l main.pl --goal main.
